[[permission]]
identifier = "allow-save-file"
description = "Enables the save_file, overwrite_file, pick_directory, save_file_to_dir, and custom_relaunch commands"
commands.allow = ["save_file", "overwrite_file", "pick_directory", "save_file_to_dir", "custom_relaunch"]

